#!/usr/bin/env bash
# Generate upstream-facing config fragments from the control plane policy files.
#
# Reads: policies/logical-models.example.yaml
#        policies/route-policies.example.yaml
#        policies/provider-pools.example.yaml
#
# Outputs:
#   1. A Bifrost config.json fragment (verified format — see docs/capability-audit.md
#      for authoritative struct definitions)
#   2. A New-API channel guidance summary (human-readable, for manual or
#      API-based import)
#
# This script uses simple bash text processing. For production use with complex
# YAML, consider migrating to a Python/Go tool with a proper YAML parser.
#
# DOES NOT REQUIRE: a running stack or any secrets.
#
# Usage:
#   ./generate-config.sh
#   ./generate-config.sh --output-dir /tmp/generated

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
POLICIES_DIR="$REPO_ROOT/policies"
OUTPUT_DIR="${1:-$REPO_ROOT/generated}"

# ── Color codes ───────────────────────────────────────────
if [ -t 1 ]; then
    GREEN='\033[0;32m'
    CYAN='\033[0;36m'
    YELLOW='\033[0;33m'
    RESET='\033[0m'
else
    GREEN='' CYAN='' YELLOW='' RESET=''
fi

info()  { printf "${CYAN}[INFO]${RESET} %s\n" "$1"; }
warn()  { printf "${YELLOW}[WARN]${RESET} %s\n" "$1"; }
ok()    { printf "${GREEN}[DONE]${RESET} %s\n" "$1"; }

# ── Validate inputs ──────────────────────────────────────
MODELS_FILE="$POLICIES_DIR/logical-models.example.yaml"
ROUTES_FILE="$POLICIES_DIR/route-policies.example.yaml"
POOLS_FILE="$POLICIES_DIR/provider-pools.example.yaml"

for f in "$MODELS_FILE" "$ROUTES_FILE" "$POOLS_FILE"; do
    if [ ! -f "$f" ]; then
        echo "ERROR: Required policy file not found: $f"
        echo "Copy .example.yaml files and customize, or ensure policies/ is populated."
        exit 1
    fi
done

mkdir -p "$OUTPUT_DIR"
info "Policy dir: $POLICIES_DIR"
info "Output dir: $OUTPUT_DIR"
echo ""

# ── Helper: extract simple YAML values ───────────────────
# This is intentionally simple. It handles flat key: value lines only.
# For nested structures we use grep + awk patterns.
yaml_value() {
    local file="$1" key="$2"
    grep "^    ${key}:" "$file" | head -1 | sed 's/.*: *//' | tr -d '"'
}

# ── 1. Generate Bifrost config fragment ──────────────────
info "Generating Bifrost config fragment..."

BIFROST_OUT="$OUTPUT_DIR/bifrost-config-fragment.json"
cat > "$BIFROST_OUT" << 'HEADER'
// Bifrost config.json fragment (verified format)
// Generated by control-plane/scripts/sync/generate-config.sh
//
// NOTE: This script outputs providers as a JSON array, but Bifrost expects
// an object keyed by provider name. The Phase 3 Go replacement will produce
// the correct format. See docs/capability-audit.md for verified Bifrost structs.
//
// Merge these entries into your Bifrost config.json providers section.
// API keys must be filled in manually — they are NOT stored in policy files.
HEADER

# Build a simplified providers array from pool definitions
echo '{' >> "$BIFROST_OUT"
echo '  "// GENERATED FROM": "policies/provider-pools.example.yaml",' >> "$BIFROST_OUT"
echo '  "providers": [' >> "$BIFROST_OUT"

# Parse provider pools — extract provider entries
# YAML structure: 6-space "- id:", 8-space properties, 10-space nested values
FIRST_PROVIDER=true
PROV_ID="" PROV_TYPE="" PROV_URL="" PROV_TIMEOUT="" PROV_RETRIES=""
while IFS= read -r line; do
    # Strip inline comments for cleaner parsing
    clean=$(echo "$line" | sed 's/ *#.*//')

    # Match "      - id: <name>" (6-space indent, start of provider block)
    if echo "$clean" | grep -qE '^ {4,6}- id:'; then
        # If we have a pending provider from the previous block, emit it now
        if [ -n "$PROV_ID" ] && [ -n "$PROV_TYPE" ]; then
            if [ "$FIRST_PROVIDER" = true ]; then
                FIRST_PROVIDER=false
            else
                echo '    ,' >> "$BIFROST_OUT"
            fi
            cat >> "$BIFROST_OUT" << EOF
    {
      "id": "$PROV_ID",
      "model_provider": "$PROV_TYPE",
      "base_url": "$PROV_URL",
      "api_key": "FILL_IN_YOUR_API_KEY",
      "network_config": {
        "max_retries": ${PROV_RETRIES:-2},
        "default_request_timeout_in_seconds": ${PROV_TIMEOUT:-60}
      }
    }
EOF
        fi
        PROV_ID=$(echo "$clean" | sed 's/.*- id: *//')
        PROV_TYPE="" PROV_URL="" PROV_TIMEOUT="" PROV_RETRIES=""
    elif [ -n "$PROV_ID" ]; then
        case "$clean" in
            *type:*)
                PROV_TYPE=$(echo "$clean" | sed 's/.*type: *//' | tr -d '"') ;;
            *base_url:*)
                PROV_URL=$(echo "$clean" | sed 's/.*base_url: *//' | tr -d '"') ;;
            *default_request_timeout_in_seconds:*)
                PROV_TIMEOUT=$(echo "$clean" | sed 's/.*: *//') ;;
            *max_retries:*)
                PROV_RETRIES=$(echo "$clean" | sed 's/.*: *//') ;;
        esac
    fi
done < "$POOLS_FILE"

# Emit the last provider if pending
if [ -n "$PROV_ID" ] && [ -n "$PROV_TYPE" ]; then
    if [ "$FIRST_PROVIDER" = true ]; then
        FIRST_PROVIDER=false
    else
        echo '    ,' >> "$BIFROST_OUT"
    fi
    cat >> "$BIFROST_OUT" << EOF
    {
      "id": "$PROV_ID",
      "model_provider": "$PROV_TYPE",
      "base_url": "$PROV_URL",
      "api_key": "FILL_IN_YOUR_API_KEY",
      "network_config": {
        "max_retries": ${PROV_RETRIES:-2},
        "default_request_timeout_in_seconds": ${PROV_TIMEOUT:-60}
      }
    }
EOF
fi

echo '  ]' >> "$BIFROST_OUT"
echo '}' >> "$BIFROST_OUT"

ok "Bifrost config fragment -> $BIFROST_OUT"

# ── 2. Generate New-API channel guidance ─────────────────
info "Generating New-API channel guidance..."

NEWAPI_OUT="$OUTPUT_DIR/newapi-channel-guidance.txt"
cat > "$NEWAPI_OUT" << 'HEADER'
# New-API Channel Guidance
# Generated by control-plane/scripts/sync/generate-config.sh
#
# Create these channels in New-API via admin UI or API.
# See: scripts/sync/sync-newapi-channels.sh for automated creation.
#
# Channel structure: each channel points to Bifrost at its internal URL.
# Model mapping translates logical names to upstream model identifiers.
HEADER

echo "" >> "$NEWAPI_OUT"

# Group models by channel
for CHANNEL in "bifrost-premium" "bifrost-standard" "bifrost-risky"; do
    echo "=== Channel: $CHANNEL ===" >> "$NEWAPI_OUT"
    echo "  Base URL: http://bifrost:8080 (internal)" >> "$NEWAPI_OUT"
    echo "  Type: OpenAI-compatible (type=1)" >> "$NEWAPI_OUT"
    echo "  Models:" >> "$NEWAPI_OUT"

    # Extract models assigned to this channel
    CURRENT_MODEL=""
    while IFS= read -r line; do
        # Detect model name (indented with 2 spaces, ends with colon)
        if echo "$line" | grep -qE '^  [a-z].*:$'; then
            CURRENT_MODEL=$(echo "$line" | sed 's/^ *//' | tr -d ':')
        fi
        if echo "$line" | grep -q "channel: $CHANNEL" && [ -n "$CURRENT_MODEL" ]; then
            # Find the upstream_model for this logical model
            UPSTREAM=$(grep -A5 "^  ${CURRENT_MODEL}:" "$MODELS_FILE" | grep "upstream_model:" | head -1 | sed 's/.*: *//' | tr -d '"')
            echo "    $CURRENT_MODEL -> $UPSTREAM" >> "$NEWAPI_OUT"
        fi
    done < "$MODELS_FILE"

    echo "" >> "$NEWAPI_OUT"
done

# Add model_mapping JSON snippet for easy copy-paste
echo "=== Model Mapping JSON (for API sync) ===" >> "$NEWAPI_OUT"
echo '{' >> "$NEWAPI_OUT"

FIRST=true
CURRENT_MODEL=""
while IFS= read -r line; do
    if echo "$line" | grep -qE '^  [a-z].*:$'; then
        CURRENT_MODEL=$(echo "$line" | sed 's/^ *//' | tr -d ':')
    fi
    if echo "$line" | grep -q "upstream_model:" && [ -n "$CURRENT_MODEL" ]; then
        UPSTREAM=$(echo "$line" | sed 's/.*: *//' | tr -d '"')
        if [ "$FIRST" = true ]; then
            FIRST=false
        else
            echo ',' >> "$NEWAPI_OUT"
        fi
        printf '  "%s": "%s"' "$CURRENT_MODEL" "$UPSTREAM" >> "$NEWAPI_OUT"
    fi
done < "$MODELS_FILE"

echo '' >> "$NEWAPI_OUT"
echo '}' >> "$NEWAPI_OUT"

ok "New-API channel guidance -> $NEWAPI_OUT"

# ── 3. Generate model list summary ──────────────────────
info "Generating model summary..."

SUMMARY_OUT="$OUTPUT_DIR/model-summary.txt"
cat > "$SUMMARY_OUT" << 'HEADER'
# Logical Model Summary
# Generated by control-plane/scripts/sync/generate-config.sh
HEADER

printf "\n%-20s %-30s %-20s %-8s %s\n" "Logical Name" "Upstream Model" "Channel" "Risk" "Unofficial" >> "$SUMMARY_OUT"
printf "%-20s %-30s %-20s %-8s %s\n" "--------------------" "------------------------------" "--------------------" "--------" "----------" >> "$SUMMARY_OUT"

CURRENT_MODEL=""
UPSTREAM="" CHAN="" RISK="" UNOFFICIAL=""
while IFS= read -r line; do
    if echo "$line" | grep -qE '^  [a-z].*:$'; then
        # Print previous model if we have one
        if [ -n "$CURRENT_MODEL" ] && [ -n "$UPSTREAM" ]; then
            printf "%-20s %-30s %-20s %-8s %s\n" "$CURRENT_MODEL" "$UPSTREAM" "$CHAN" "$RISK" "$UNOFFICIAL" >> "$SUMMARY_OUT"
        fi
        CURRENT_MODEL=$(echo "$line" | sed 's/^ *//' | tr -d ':')
        UPSTREAM="" CHAN="" RISK="" UNOFFICIAL=""
    fi
    case "$line" in
        *upstream_model:*)    UPSTREAM=$(echo "$line" | sed 's/.*: *//' | tr -d '"') ;;
        *"    channel:"*)     CHAN=$(echo "$line" | sed 's/.*channel: *//' | tr -d '"') ;;
        *risk_level:*)        RISK=$(echo "$line" | sed 's/.*: *//' | tr -d '"') ;;
        *unofficial_allowed:*) UNOFFICIAL=$(echo "$line" | sed 's/.*: *//' | tr -d '"') ;;
    esac
done < "$MODELS_FILE"
# Print last model
if [ -n "$CURRENT_MODEL" ] && [ -n "$UPSTREAM" ]; then
    printf "%-20s %-30s %-20s %-8s %s\n" "$CURRENT_MODEL" "$UPSTREAM" "$CHAN" "$RISK" "$UNOFFICIAL" >> "$SUMMARY_OUT"
fi

ok "Model summary -> $SUMMARY_OUT"

# ── Done ─────────────────────────────────────────────────
echo ""
info "Generated files:"
ls -la "$OUTPUT_DIR"/
echo ""
info "Next steps:"
info "  1. Review generated files in $OUTPUT_DIR/"
info "  2. Fill in API keys in the Bifrost config fragment"
info "  3. Import channels via: scripts/sync/sync-newapi-channels.sh"
info "  4. See scripts/sync/plan-sync.md for the full sync procedure"
